### ISSUE TITLE
Macbook Air M1 shows up as iPad

### ISSUE THREAD

**Issue by mthoodlum** [ispapp/ispapp-go-client#5]

**Comment by andrewhodel** [comment]
That's not the go client David, that's Apple's swift language and the Catalyst builds for the M1 processors.

They need to fix what is reported from the OS, you can file a bug with Apple.

**Comment by andrewhodel** [comment]
<img width="749" alt="Screen Shot 2022-04-02 at 2 43 01 PM" src="https://user-images.githubusercontent.com/741705/161366615-dbb58b77-4e25-46b2-a262-2b80ab5c6c2a.png">

**Comment by mthoodlum** [comment]
Where is the repo for this client type?

**Comment by andrewhodel** [comment]
It's on my laptop and my github.

It's just the same as an example from the internet.  There's nothing to making an HTTP request with the sensor data.

**Comment by andrewhodel** [comment]
I say kill the guy that wants to stab about hearing humor me though, but nobody wants to invest in driverless and the general is keeping my money to maintain a problem that's fixed there.

But nobody can improve anything in technology because Apple won't fix the work and it's all done already.

But all of a sudden it's a big deal for you right?

**Comment by andrewhodel** [comment]
You don't even know what language this is in, yet you hear something and act this way.

I won't stand for that.

**Comment by andrewhodel** [comment]
Real work on a keyboard can make the smoke problem go away, 3d and dust engineering.

That's the truth of it, the fact of it is ruin Andrew's work because we didn't pay fairly and now he still works.

Humor that, it's a comedy show right?
